import type { Employee, Task } from "./supabase/types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    name: "Sariph Shrestha",
    nickname: "Sariph",
    email: "sariph@company.com",
    avatar_url: null,
    slack_id: null,
    discord_id: null,
    phone: null,
    whatsapp: null,
    role: "manager",
    avg_variance_ratio: 1.05,
    avg_response_minutes: 3,
    tasks_completed: 6,
    on_time_percentage: 95,
    is_active: true,
    created_at: hoursAgo(720),
    updated_at: hoursAgo(1),
  },
  {
    id: "emp-2",
    name: "Prashant Parajuli",
    nickname: "Prashant",
    email: "prashant@company.com",
    avatar_url: null,
    slack_id: null,
    discord_id: null,
    phone: null,
    whatsapp: null,
    role: "developer",
    avg_variance_ratio: 1.1,
    avg_response_minutes: 5,
    tasks_completed: 12,
    on_time_percentage: 83,
    is_active: true,
    created_at: hoursAgo(720),
    updated_at: hoursAgo(2),
  },
  {
    id: "emp-3",
    name: "Aayush Poudel",
    nickname: "Aayush",
    email: "aayush@company.com",
    avatar_url: null,
    slack_id: null,
    discord_id: null,
    phone: null,
    whatsapp: null,
    role: "developer",
    avg_variance_ratio: 0.9,
    avg_response_minutes: 4,
    tasks_completed: 9,
    on_time_percentage: 91,
    is_active: true,
    created_at: hoursAgo(720),
    updated_at: hoursAgo(1),
  },
  {
    id: "emp-4",
    name: "Sushant Regmi",
    nickname: "Sushant",
    email: "sushant@company.com",
    avatar_url: null,
    slack_id: null,
    discord_id: null,
    phone: null,
    whatsapp: null,
    role: "developer",
    avg_variance_ratio: 1.2,
    avg_response_minutes: 8,
    tasks_completed: 8,
    on_time_percentage: 78,
    is_active: true,
    created_at: hoursAgo(720),
    updated_at: hoursAgo(3),
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    parent_id: null,
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "in_progress",
    priority: "P1",
    assignee_id: "emp-2",
    created_by_id: "emp-1",
    ai_estimate_hours: 6,
    actual_hours: null,
    due_at: hoursFromNow(48),
    started_at: hoursAgo(6),
    completed_at: null,
    tracker_enabled: true,
    tracker_interval_minutes: 60,
    current_escalation: "slack",
    last_ping_at: hoursAgo(0.5),
    last_response_at: hoursAgo(0.3),
    progress_percent: 40,
    sort_order: 0,
    created_at: hoursAgo(24),
    updated_at: hoursAgo(0.3),
    assignee: mockEmployees[1],
    subtasks: [],
  },
  {
    id: "task-2",
    parent_id: null,
    title: "Build user dashboard",
    description: "Create the main dashboard with analytics widgets",
    status: "in_progress",
    priority: "P1",
    assignee_id: "emp-3",
    created_by_id: "emp-1",
    ai_estimate_hours: 12,
    actual_hours: null,
    due_at: hoursFromNow(96),
    started_at: hoursAgo(10),
    completed_at: null,
    tracker_enabled: true,
    tracker_interval_minutes: 60,
    current_escalation: "slack",
    last_ping_at: hoursAgo(0.2),
    last_response_at: hoursAgo(0.1),
    progress_percent: 25,
    sort_order: 1,
    created_at: hoursAgo(20),
    updated_at: hoursAgo(0.1),
    assignee: mockEmployees[2],
    subtasks: [
      {
        id: "task-2a",
        parent_id: "task-2",
        title: "Dashboard layout and navigation",
        description: null,
        status: "done",
        priority: "P1",
        assignee_id: "emp-3",
        created_by_id: "emp-1",
        ai_estimate_hours: 3,
        actual_hours: 2.5,
        due_at: hoursAgo(2),
        started_at: hoursAgo(10),
        completed_at: hoursAgo(2),
        tracker_enabled: false,
        tracker_interval_minutes: 60,
        current_escalation: "slack",
        last_ping_at: null,
        last_response_at: null,
        progress_percent: 100,
        sort_order: 0,
        created_at: hoursAgo(20),
        updated_at: hoursAgo(2),
        assignee: mockEmployees[2],
      },
      {
        id: "task-2b",
        parent_id: "task-2",
        title: "Analytics charts component",
        description: null,
        status: "in_progress",
        priority: "P1",
        assignee_id: "emp-3",
        created_by_id: "emp-1",
        ai_estimate_hours: 4,
        actual_hours: null,
        due_at: hoursFromNow(48),
        started_at: hoursAgo(4),
        completed_at: null,
        tracker_enabled: true,
        tracker_interval_minutes: 60,
        current_escalation: "slack",
        last_ping_at: null,
        last_response_at: null,
        progress_percent: 50,
        sort_order: 1,
        created_at: hoursAgo(20),
        updated_at: hoursAgo(1),
        assignee: mockEmployees[2],
      },
      {
        id: "task-2c",
        parent_id: "task-2",
        title: "Real-time data integration",
        description: null,
        status: "pending",
        priority: "P2",
        assignee_id: "emp-4",
        created_by_id: "emp-1",
        ai_estimate_hours: 5,
        actual_hours: null,
        due_at: hoursFromNow(72),
        started_at: null,
        completed_at: null,
        tracker_enabled: true,
        tracker_interval_minutes: 120,
        current_escalation: "slack",
        last_ping_at: null,
        last_response_at: null,
        progress_percent: 0,
        sort_order: 2,
        created_at: hoursAgo(20),
        updated_at: hoursAgo(20),
        assignee: mockEmployees[3],
      },
    ],
  },
  {
    id: "task-3",
    parent_id: null,
    title: "Fix payment webhook handler",
    description: "Webhook fails silently on duplicate events",
    status: "pending",
    priority: "P0",
    assignee_id: "emp-4",
    created_by_id: "emp-1",
    ai_estimate_hours: 3,
    actual_hours: null,
    due_at: hoursFromNow(24),
    started_at: null,
    completed_at: null,
    tracker_enabled: true,
    tracker_interval_minutes: 30,
    current_escalation: "slack",
    last_ping_at: null,
    last_response_at: null,
    progress_percent: 0,
    sort_order: 2,
    created_at: hoursAgo(8),
    updated_at: hoursAgo(8),
    assignee: mockEmployees[3],
    subtasks: [],
  },
  {
    id: "task-4",
    parent_id: null,
    title: "API rate limiting",
    description: "Implement rate limiting middleware for all public endpoints",
    status: "pending",
    priority: "P2",
    assignee_id: "emp-2",
    created_by_id: "emp-1",
    ai_estimate_hours: 4,
    actual_hours: null,
    due_at: hoursFromNow(120),
    started_at: null,
    completed_at: null,
    tracker_enabled: true,
    tracker_interval_minutes: 120,
    current_escalation: "slack",
    last_ping_at: null,
    last_response_at: null,
    progress_percent: 0,
    sort_order: 3,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
    assignee: mockEmployees[1],
    subtasks: [],
  },
  {
    id: "task-5",
    parent_id: null,
    title: "Database migration scripts",
    description: "Write migration scripts for v2 schema changes",
    status: "acknowledged",
    priority: "P2",
    assignee_id: "emp-3",
    created_by_id: "emp-1",
    ai_estimate_hours: 5,
    actual_hours: null,
    due_at: hoursFromNow(72),
    started_at: null,
    completed_at: null,
    tracker_enabled: true,
    tracker_interval_minutes: 60,
    current_escalation: "slack",
    last_ping_at: null,
    last_response_at: null,
    progress_percent: 10,
    sort_order: 4,
    created_at: hoursAgo(4),
    updated_at: hoursAgo(3),
    assignee: mockEmployees[2],
    subtasks: [],
  },
];
